#58 Feat: update flow
GolosChain/registration-service pull request #59
Opened 2019-02-25 16:20 UTC by IvanBlacky

2019-02-25 17:29 UTC, bacher requested changes

2019-02-25 17:29 UTC, Bacher commented on src/services/Connector.js
> +            /* !user ||
Такого роде комментарии нужно сопровождать комментарием объяснением и еще // TODO: или // FIXME: в начале.

2019-02-25 17:29 UTC, Bacher commented on src/services/Connector.js
> +        if (user) return await User.findOne({ user }, {}, { sort: { _id: -1 } });
```
if (user) {
    return await User.findOne({ user }, {}, { sort: { _id: -1 } });
}
```

2019-02-25 17:29 UTC, Bacher commented on Readme.md
> +addUsername:                   // Второй шаг регистрации, верификация аккаунта (кроме стратегии smsFromUser).
Убежало форматирование куда-то

2019-02-26 09:21 UTC, Format-X22 requested changes

2019-02-26 09:21 UTC, Format-X22 commented on src/models/User.js
> +                    phone: 1,
Ошибка - нужно использовать два индекса вместо составного т.к. у нас, судя по коду ниже, происходит поиск по одному полю - либо тому либо сему.

2019-02-26 09:21 UTC, Format-X22 commented on src/services/Connector.js
> +        return await User.findOne({ phone }, {}, { sort: { _id: -1 } });
Этот метод предполагает вызов без параметра phone, а значит ни к чему дергать поиск по телефону если вдруг он пуст.

2019-02-26 09:24 UTC, Format-X22 approved these changes

2019-02-26 09:25 UTC, bacher approved these changes

2019-02-26 09:57 UTC, merged