#60 Feat: improve state and step mechanics
GolosChain/registration-service pull request #61
Opened 2019-03-15 17:10 UTC by IvanBlacky

2019-03-15 17:12 UTC, bacher requested changes

2019-03-15 17:12 UTC, Bacher commented on src/controllers/SmsFromUser.js
> +        model.state = 'toBlockChain';
А вы не юзаете ENUM вида

```javascript
const REG_STATE = {
    TO_BLOCK_CHAIN: 'toBlockChain',
	VERIFY: 'verify',
    ...
}
```
?

и было бы
```javascript
model.state = REG_STATE.TO_BLOCK_CHAIN;
```

2019-03-15 17:13 UTC, bacher requested changes

2019-03-15 17:13 UTC, Bacher commented on src/controllers/SmsFromUser.js
> +        model.state = 'toBlockChain';
Плюсы это-го метода - нельзя сделать опечатку, IDE отметит несоответствие. Ну обычно

2019-03-15 17:15 UTC, bacher requested changes

2019-03-15 17:15 UTC, Bacher commented on src/controllers/SmsToUser.js
> +            throw { ...errors.E403.error, nextSmsRetry: this._getSmsRetryState(model) };
Лучше в две строки, будет читаемее

```javascript
throw {
    ...errors.E403.error,
    nextSmsRetry: this._getSmsRetryState(model),
};
```

сейчас просто глаза разбегаются от точек и запятых.

2019-03-15 17:18 UTC, bacher requested changes

2019-03-15 17:18 UTC, Bacher commented on src/controllers/SmsToUser.js
> +                return null;
Не очень понятно, в одном случае вернется результат из `this._calcNextSmsRetry` во втром случае вернется `null` в третьем случае вернется `undefined`.

Лучше явно указать возврщаемое значение.

Если еще и инвертировать условие то получится и короче:

```javascript
if (recentModel.smsCodeResendCount > env.GLS_SMS_RESEND_CODE_MAX) {
    return null;
}

return this._calcNextSmsRetry(recentModel);
```

2019-03-18 08:52 UTC, IvanBlacky commented on src/controllers/SmsToUser.js
> +                return null;
Поведение с тремя возможными значениями задумано: `undefined` вернется, если получение данных не актуально для данного этапа регистрации, иначе -- вернется либо значение, либо `null` как указание на невозможность еще одной попытки.

2019-03-18 09:05 UTC, bacher approved these changes

2019-03-18 09:06 UTC, Format-X22 approved these changes

2019-03-18 09:09 UTC, merged