#69 Feat: add tests, add userId support
GolosChain/registration-service pull request #70
Opened 2019-04-26 15:22 UTC by IvanBlacky

2019-04-26 15:24 UTC, IvanBlacky commented
Also closes issues #66 #67

2019-04-26 15:38 UTC, bacher requested changes

2019-04-26 15:38 UTC, Bacher commented on src/controllers/AbstractSms.js
> +        } catch (e) {
error

можно вроде в WebStorm поправить дефолтный шаблон try/catch чтобы сразу error писал.

2019-04-26 15:38 UTC, Bacher commented on src/controllers/AbstractSms.js
> +            } else {
Можно без else и вообще инвертированные условия плохо читаются, я бы записал наоборот:

```javascript
const isOccupied = await this._isUsernameOccupied(accountName);

if (isOccupied) {
    return await this._generateNewUsername();
}

return accountName;
```

Так сохраняется логическая последовательность действий.

2019-04-26 15:38 UTC, Bacher commented on tests/utils.js
> +    } catch (e) {
error

2019-04-26 15:38 UTC, Bacher commented on tests/utils.js
> +        if (!occupied) {
Тут аналогично.

2019-04-26 15:52 UTC, Format-X22 requested changes

2019-04-26 15:52 UTC, Format-X22 commented on .env.example
> +GLS_CREATOR_KEY=
Перенос строки бы.

2019-04-26 15:52 UTC, Format-X22 commented on Readme.md
> +toBlockChain:         // Последний шаг регистрации, запись в блокчейн. Возвращает userId и username
Последний шаг регистрации, запись в блокчейн, возвращает userId и username

Вообще не критично, но красивее

2019-04-26 15:52 UTC, Format-X22 commented on Readme.md
> +-   `GLS_CREATOR_NAME` - имя аккаунта, выполняющего `newaccount`
Сложно с ходу понять что за newaccount. Обычно это называется аккаунт регистратора и тп.

2019-04-26 15:52 UTC, Format-X22 commented on Readme.md
> +-   `GLS_CREATOR_KEY` - приватный ключ аккаунта, выполняющего `newaccount`
Аналогично.

2019-04-26 15:52 UTC, Format-X22 commented on src/controllers/AbstractSms.js
> +                throw {
Что-то совсем треугольная вложенность высокая, упросить бы как-то.

2019-04-26 15:52 UTC, Format-X22 commented on src/controllers/AbstractSms.js
> +            throw {
В одну строку можно.

2019-04-26 15:53 UTC, IvanBlacky commented on Readme.md
> +-   `GLS_CREATOR_NAME` - имя аккаунта, выполняющего `newaccount`
Есть уже аккаунт регистратора, а в БЧ он называется именно creator

2019-04-26 15:53 UTC, IvanBlacky commented on Readme.md
> +-   `GLS_CREATOR_KEY` - приватный ключ аккаунта, выполняющего `newaccount`
Аналогично ответил выше

2019-05-15 10:12 UTC, IvanBlacky commented
Closes #72

2019-05-15 10:16 UTC, bacher approved these changes

2019-05-15 15:05 UTC, Format-X22 approved these changes

2019-05-15 15:06 UTC, merged