Add user check get state
GolosChain/registration-service pull request #77
Opened 2019-06-06 09:06 UTC by IvanBlacky

2019-06-06 09:09 UTC, Bacher commented on src/controllers/Abstract.js
> +        return Promise.race([defaultTimeout(), prismResponse()]);
А это второе место уже где такого рода timeout используется?

2019-06-06 09:25 UTC, bacher approved these changes

2019-06-06 09:36 UTC, Format-X22 requested changes

2019-06-06 09:36 UTC, Format-X22 commented on src/controllers/Abstract.js
> +        const prismResponse = async () => {
Лучше в методы вынести, причём не только из эстетических соображений, но и работать будет эффективнее по ресурсам.

2019-06-07 15:14 UTC, Format-X22 requested changes

2019-06-07 15:14 UTC, Format-X22 commented on src/controllers/Abstract.js
> +    _defaultTimeout(maxWait) {
then-sleep пакет, он у нас в разных местах используется. С ним этот метод будет не нужен.

2019-06-07 15:32 UTC, Format-X22 approved these changes

2019-06-07 15:32 UTC, merged